version: "3.8"

services:
  database:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hogarpeludo
      MYSQL_USER: hogarpeludouser
      MYSQL_PASSWORD: hogarpeludo2024
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hogarpeludo-net

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_container
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - hogarpeludo-net

  backend:
    build: .
    container_name: node_backend
    restart: always
    depends_on:
      - database
      - keycloak
    environment:
      DB_HOST: database
      DB_USER: hogarpeludouser
      DB_PASSWORD: hogarpeludo2024
      DB_NAME: hogarpeludo
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["node", "src/app.js"]
    networks:
      - hogarpeludo-net

volumes:
  mysql_data:
  keycloak_data:

networks:
  hogarpeludo-net:
